# Generated by Django 5.2.5 on 2025-09-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
